---
  dependencies: []
  
  galaxy_info:
    author: venerari
    description: wordpress for RHEL/CentOS.
    company: "venerari"
    license: "license (BSD, MIT)"
    min_ansible_version: 2.1
    platforms:
      - name: EL
        versions:
        - 5
        - 6
        - 7
    galaxy_tags:
      - wordpress
     