---

- name: Include Redhat vars
  include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Add the web1 to hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ web1ip }} {{ web1name }}'

- name: Add the web2 to hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ web2ip }} {{ web2name }}'

- name: Add the mysql to hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ mysqlip }} {{ mysqlname }}'

- name: Stop selinux
  shell: setenforce 0
  args:
    executable: /bin/bash

- name: Template to edit selinux
  template:
    src=config.j2
    dest=/etc/selinux/config

- name: Install mariadb
  yum:  pkg=mariadb-server state=present
  when: ansible_os_family == "RedHat"

- name: Enable mariadb
  systemd: enabled=yes name=mariadb

- name: Start mariadb
  systemd: state=started name=mariadb

- name: Open tcp 3306
  firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Create db - WILL FAIL IF ALREADY DONE
  shell: mysql -e "{{ createdbandgrantuser }}"
  args:
    executable: /bin/bash
